# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x04grpc\"\r\n\x0bGrpcRequest\";\n\x0cGrpcResponse\x12\x11\n\x04\x63ode\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x02 \x01(\tB\x07\n\x05_code2>\n\x0bGrpcService\x12/\n\x04grpc\x12\x11.grpc.GrpcRequest\x1a\x12.grpc.GrpcResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRPCREQUEST._serialized_start=20
  _GRPCREQUEST._serialized_end=33
  _GRPCRESPONSE._serialized_start=35
  _GRPCRESPONSE._serialized_end=94
  _GRPCSERVICE._serialized_start=96
  _GRPCSERVICE._serialized_end=158
# @@protoc_insertion_point(module_scope)
